#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Feb 12 09:58:04 2018

@author: abuzarmahmood
"""
#Import dat ish
import numpy as np
import tables
import easygui
import os
import re
import matplotlib.pyplot as plt

plot_dir = easygui.diropenbox(msg = 'Choose directory to store the plots in')

# Ask the user for the hdf5 files that need to be plotted together
dirs = []
while True:
    dir_name = easygui.diropenbox(msg = 'Choose a directory with a hdf5 file, hit cancel to stop choosing')
    try:
        if len(dir_name) > 0:    
            dirs.append(dir_name)
    except:
        break

unique_states = []
for dir_name in dirs:
        
    # Change to the directory
    os.chdir(dir_name)
    # Locate the hdf5 file
    file_list = os.listdir('./')
    hdf5_name = ''
    for files in file_list:
        if files[-2:] == 'h5':
            hdf5_name = files

    # Open the hdf5 file
    hf5 = tables.open_file(hdf5_name, 'r') 
    states = hf5.list_nodes('/spike_trains/multinomial_hmm_results/laser_off')
    states = re.findall('\d',states.__str__())
    for i in range(len(states)):
        states[i] = int(states[i])
    unique_states.append(states)

hf5.close()
unique_states = np.unique(unique_states)

# Now run through the directories, and pull out the data
# Going to loop through each file and each model of the HMM (different number 
# of states) with on and off states separately


for num_state in unique_states:
    
    r_pearson_off = []
    p_pearson_off = []
    
    r_pearson_on = []
    p_pearson_on = []
    
    num_units_on = 0
    num_units_off = 0
    
    for dir_name in dirs:
        
            # Change to the directory
            os.chdir(dir_name)
            # Locate the hdf5 file
            file_list = os.listdir('./')
            hdf5_name = ''
            for files in file_list:
                if files[-2:] == 'h5':
                    hdf5_name = files
        
            # Open the hdf5 file
            hf5 = tables.open_file(hdf5_name, 'r')
        
            # Pull the data from the /ancillary_analysis node
            exec('r_pearson_off.append(hf5.root.spike_trains.multinomial_hmm_results.laser_off.states_%i.r_pearson[:])' % num_state)
            exec('p_pearson_off.append(hf5.root.spike_trains.multinomial_hmm_results.laser_off.states_%i.p_pearson[:])' % num_state)
            exec('r_pearson_on.append(hf5.root.spike_trains.multinomial_hmm_results.laser_on.states_%i.r_pearson[:])' % num_state)
            exec('p_pearson_on.append(hf5.root.spike_trains.multinomial_hmm_results.laser_on.states_%i.p_pearson[:])' % num_state)
            ## Also maintain a counter of the number of units in the analysis
            exec('num_units_on += hf5.root.spike_trains.multinomial_hmm_results.laser_on.states_%i.p_pearson.shape[0]' % num_state)
            exec('num_units_off += hf5.root.spike_trains.multinomial_hmm_results.laser_off.states_%i.p_pearson.shape[0]' % num_state)
    
            # Close the hdf5 file
            hf5.close()
            
    if len(unique_states)==1:
        r_pearson_off = r_pearson_off[0]
        p_pearson_off = p_pearson_off[0]
        r_pearson_on = r_pearson_on[0]
        p_pearson_on = p_pearson_on[0]
    else:
        r_pearson_off = np.concatenate(r_pearson_off,0)
        p_pearson_off = np.concatenate(p_pearson_off,0)
        r_pearson_on = np.concatenate(r_pearson_on,0)
        p_pearson_on = np.concatenate(p_pearson_on,0)
            
    fig = plt.figure()
    plt.title('Correlation, Off trials , Model states =' + str(num_state))
    plt.plot(np.mean(r_pearson_off[:, :]**2, axis = 0))
    fig.savefig(plot_dir + '/off_correlation_states%i.png' % num_state)
    plt.close('all')
    
    fig = plt.figure()
    plt.title('Correlation, On trials , Model states =' + str(num_state))
    plt.plot(np.mean(r_pearson_on[:, :]**2, axis = 0))
    fig.savefig(plot_dir + '/on_correlation_states%i.png' % num_state)
    plt.close('all')